server:
  port: 21005
spring:
  application:
    name: dataland
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
  resources:
    add-mappings: false
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.233:3306/dataland?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&useAffectedRows=true
    username: dataland
    password: dl@!@#sdsf123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 50
      initial-size: 10
      filters: stat
      max-wait: 60000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-return: false
      test-on-borrow: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      connection-init-sqls: SET NAMES utf8mb4
      log-abandoned: true
      remove-abandoned: true
      remove-abandoned-timeout: 180
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  redis:
    database: 7
    host: 192.168.1.247
    port: 6379
    timeout: 5000ms
    password: Xteam123$
logging:
  config: classpath:logback-custom.xml
log-config:
  log-home: /tmp
  log-module: ${spring.application.name}
  max-history: 30
  max-file-size: 100MB
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}[lineno:%clr(%5.5line)] %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %X{TRACE_ID}  ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
      update-strategy: ignored
sinso-getway:
  url: https://api-ap-singapore-1.getway.sinso.io/v1/upload
  token: be8445c9f1d211ecb293020017009841
dynamic:
  log-switch: true
  upload-switch: true

